export const LOAD_LIST = 'LOAD_LIST'
export const LOAD_NEWS = 'LOAD_NEWS'
export const FETCH_PENDING= 'FETCH_PENDING'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILURE = 'FETCH_FAILURE'
export const ADD_NEWS = 'ADD_NEWS'
export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_CHILD_COMMENT = 'ADD_CHILD_COMMENT'
